name: Dependent Jobs

on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "This is job-1"

    job-2:
        runs-on: ubuntu-latest
#        needs: job-1
        steps:
            - name: step1
              run: echo "This is job-2"      


