name: Javascript Actions
on: [push]

jobs:
  actions-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: sai-pranay-teja/javascript-actions@0.0.2
        with:
          name: 'pranay'
      # Use the output from the `hello` step
      - name: Get the output greeting
        run: echo "The greeting was ${{ steps.hello.outputs.greeting_value }}"
