name: Schedule-Events

on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
 hi-there:
    runs-on: ubuntu-latest
    steps:
      - name: This will give the current time
        run: echo "The current time is $(date)"


