name: Workflow contexts examples


on: [push]



jobs:
    context-workflow:
      runs-on: ubuntu-latest



      steps:
        - name: using contexts
          run: |
            echo "The event name is $EVENT_NAME"
            echo "The name of the actor is $ACTOR_NAME"
          env:
            EVENT_NAME: ${{ github.event_name }}
            ACTOR_NAME: ${{ github.actor }}